using System;
using Exchange.ConstantFunctions;
using Exchange.GlobalVariables;
using Exchange.Constants;
using System.Collections.Generic;
using System.Management.Automation;

namespace Exchange.Functions.RolesAndAccess
{
    //Add-MailboxPermission
    //Add-ManagementRoleEntry
    //Add-RoleGroupMember
    //Add-UnifiedGroupLinks
    //Disable-JournalArchiving
    //Disable-Mailbox
    //Enable-Mailbox
    //Get-AccessToCustomerDataRequest
    //Get-AddressBookPolicy
    //Get-AddressList
    //Get-AdministrativeUnit
    //Get-AuthenticationPolicy
    //Get-AuthServer
    //Get-Contact
    //Get-EmailAddressPolicy
    //Get-EventsFromEmailConfiguration
    //Get-GlobalAddressList
    //Get-LinkedUser
    //Get-Mailbox
    //Get-MailboxAutoReplyConfiguration
    //Get-MailboxCalendarConfiguration
    //Get-MailboxFolder
    //Get-MailboxJunkEmailConfiguration
    //Get-MailboxLocation
    //Get-MailboxMessageConfiguration
    //Get-MailboxPermission
    //Get-MailboxRegionalConfiguration
    //Get-MailboxSpellingConfiguration
    //Get-MailboxUserConfiguration
    //Get-MailContact
    //Get-MailUser
    //Get-ManagementRole
    //Get-ManagementRoleAssignment
    //Get-ManagementRoleEntry
    //Get-ManagementScope
    //Get-OfflineAddressBook
    //Get-OnPremisesOrganization
    //Get-PartnerApplication
    //Get-Recipient
    //Get-RoleAssignmentPolicy
    //Get-RoleGroup
    //Get-RoleGroupMember
    //Get-SiteMailbox
    //Get-SiteMailboxDiagnostics
    //Get-TenantAnalyticsConfig
    //Get-UnifiedGroup
    //Get-UnifiedGroupLinks
    //Get-User
    //Get-UserAnalyticsConfig
    //Get-UserPhoto
    //Import-RecipientDataProperty
    //New-AddressBookPolicy
    //New-AddressList
    //New-AuthenticationPolicy
    //New-EmailAddressPolicy
    //New-EOPDistributionGroup
    //New-EOPMailUser
    //New-GlobalAddressList
    //New-Mailbox
    //New-MailboxFolder
    //New-MailContact
    //New-MailUser
    //New-ManagementRole
    //New-ManagementRoleAssignment
    //New-ManagementScope
    //New-OfflineAddressBook
    //New-OnPremisesOrganization
    //New-PartnerApplication
    //New-RoleAssignmentPolicy
    //New-RoleGroup
    //New-SiteMailbox
    //New-UnifiedGroup
    //Remove-AddressBookPolicy
    //Remove-AddressList
    //Remove-AuthenticationPolicy
    //Remove-EmailAddressPolicy
    //Remove-EOPDistributionGroup
    //Remove-EOPMailUser
    //Remove-GlobalAddressList
    //Remove-HybridConfiguration
    //Remove-Mailbox
    //Remove-MailboxPermission
    //Remove-MailboxUserConfiguration
    //Remove-MailContact
    //Remove-MailUser
    //Remove-ManagementRole
    //Remove-ManagementRoleAssignment
    //Remove-ManagementRoleEntry
    //Remove-ManagementScope
    //Remove-OfflineAddressBook
    //Remove-OnPremisesOrganization
    //Remove-PartnerApplication
    //Remove-RoleAssignmentPolicy
    //Remove-RoleGroup
    //Remove-RoleGroupMember
    //Remove-UnifiedGroup
    //Remove-UnifiedGroupLinks
    //Remove-UserPhoto
    //Set-AccessToCustomerDataRequest
    //Set-AddressBookPolicy
    //Set-AddressList
    //Set-AuthenticationPolicy
    //Set-Contact
    //Set-EmailAddressPolicy
    //Set-EOPDistributionGroup
    //Set-EOPGroup
    //Set-EOPMailUser
    //Set-EOPUser
    //Set-EventsFromEmailConfiguration
    //Set-GlobalAddressList
    //Set-LinkedUser
    //Set-Mailbox
    //Set-MailboxAutoReplyConfiguration
    //Set-MailboxCalendarConfiguration
    //Set-MailboxJunkEmailConfiguration
    //Set-MailboxMessageConfiguration
    //Set-MailboxRegionalConfiguration
    //Set-MailboxSpellingConfiguration
    //Set-MailContact
    //Set-MailUser
    //Set-ManagementRoleAssignment
    //Set-ManagementRoleEntry
    //Set-ManagementScope
    //Set-OfflineAddressBook
    //Set-OnPremisesOrganization
    //Set-PartnerApplication
    //Set-RoleAssignmentPolicy
    //Set-RoleGroup
    //Set-SiteMailbox
    //Set-TenantAnalyticsConfig
    //Set-UnifiedGroup
    //Set-User
    //Set-UserAnalyticsConfig
    //Set-UserPhoto
    //Test-ApplicationAccessPolicy
    //Test-SiteMailbox
    //Undo-SoftDeletedMailbox
    //Undo-SoftDeletedUnifiedGroup
    //Update-EOPDistributionGroupMember
    //Update-HybridConfiguration
    //Update-Recipient
    //Update-RoleGroupMember
    //Update-SiteMailbox
}