using System;
using Exchange.ConstantFunctions;
using Exchange.GlobalVariables;
using Exchange.Constants;
using System.Collections.Generic;
using System.Management.Automation;

namespace Exchange.functions.ServerStatus
{
    //Delete-QuarantineMessage
    //Enable-OrganizationCustomization
    //Export-QuarantineMessage
    //Get-AdvancedThreatProtectionDocumentDetail
    //Get-AdvancedThreatProtectionDocumentReport
    //Get-AdvancedThreatProtectionTrafficReport
    //Get-ApplicationAccessPolicy
    //Get-ATPTotalTrafficReport
    //Get-CompromisedUserAggregateReport
    //Get-CompromisedUserDetailReport
    //Get-ConnectionByClientTypeDetailReport
    //Get-ConnectionByClientTypeReport
    //Get-CsActiveUserReport
    //Get-CsAVConferenceTimeReport
    //Get-CsClientDeviceDetailReport
    //Get-CsClientDeviceReport
    //Get-CsConferenceReport
    //Get-CsP2PAVTimeReport
    //Get-CsP2PSessionReport
    //Get-CsPSTNConferenceTimeReport
    //Get-CsPSTNUsageDetailReport
    //Get-CsUserActivitiesReport
    //Get-CsUsersBlockedReport
    //Get-DataClassificationConfig
    //Get-DataRetentionReport
    //Get-DlpDetailReport
    //Get-DlpDetectionsReport
    //Get-DlpSiDetectionsReport
    //Get-GroupActivityReport
    //Get-HistoricalSearch
    //Get-LicenseVsUsageSummaryReport
    //Get-MailboxActivityReport
    //Get-MailboxStatistics
    //Get-MailboxUsageDetailReport
    //Get-MailboxUsageReport
    //Get-MailDetailATPReport
    //Get-MailDetailDlpPolicyReport
    //Get-MailDetailMalwareReport
    //Get-MailDetailSpamReport
    //Get-MailDetailTransportRuleReport
    //Get-MailFilterListReport
    //Get-MailflowStatusReport
    //Get-MailTrafficATPReport
    //Get-MailTrafficPolicyReport
    //Get-MailTrafficReport
    //Get-MailTrafficSummaryReport
    //Get-MailTrafficTopReport
    //Get-MessageTrace
    //Get-MessageTraceDetail
    //Get-MxRecordReport
    //Get-O365ClientBrowserDetailReport
    //Get-O365ClientBrowserReport
    //Get-O365ClientOSDetailReport
    //Get-O365ClientOSReport
    //Get-OrganizationalUnit
    //Get-OutboundConnectorReport
    //Get-QuarantineMessage
    //Get-QuarantineMessageHeader
    //Get-RecipientStatisticsReport
    //Get-ReportExecutionInstance
    //Get-SafeLinksAggregateReport
    //Get-SafeLinksDetailReport
    //Get-SCInsights
    //Get-SearchDocumentFormat
    //Get-SecurityPrincipal
    //Get-ServiceDeliveryReport
    //Get-SmimeConfig
    //Get-SPOActiveUserReport
    //Get-SpoofMailReport
    //Get-SPOSkyDriveProDeployedReport
    //Get-SPOSkyDriveProStorageReport
    //Get-SPOTeamSiteDeployedReport
    //Get-SPOTeamSiteStorageReport
    //Get-SPOTenantStorageMetricReport
    //Get-StaleMailboxDetailReport
    //Get-StaleMailboxReport
    //Get-SupervisoryReviewOverallProgressReport
    //Get-SupervisoryReviewPolicyReport
    //Get-SupervisoryReviewReport
    //Get-SupervisoryReviewTopCasesReport
    //New-ApplicationAccessPolicy
    //New-MailMessage
    //Preview-QuarantineMessage
    //Release-QuarantineMessage
    //Remove-ApplicationAccessPolicy
    //Set-ApplicationAccessPolicy
    //Set-CASMailboxPlan
    //Set-SmimeConfig
    //Start-HistoricalSearch
    //Stop-HistoricalSearch
    //Test-MAPIConnectivity
}