using System;
using Exchange.ConstantFunctions;
using Exchange.GlobalVariables;
using Exchange.Constants;
using System.Collections.Generic;
using System.Management.Automation;

namespace Exchange.functions.TransportMailflow
{
    //Disable-AntiPhishRule
    //Disable-HostedContentFilterRule
    //Disable-HostedOutboundSpamFilterRule
    //Disable-InboxRule
    //Disable-MalwareFilterRule
    //Disable-SafeAttachmentRule
    //Disable-SafeLinksRule
    //Disable-SweepRule
    //Disable-TransportRule
    //Enable-AntiPhishRule
    //Enable-ComplianceTagStorage
    //Enable-HostedContentFilterRule
    //Enable-HostedOutboundSpamFilterRule
    //Enable-InboxRule
    //Enable-MalwareFilterRule
    //Enable-SafeAttachmentRule
    //Enable-SafeLinksRule
    //Enable-SweepRule
    //Enable-TransportRule
    //Execute-AzureADLabelSync
    //Export-DlpPolicyCollection
    //Export-TransportRuleCollection
    //Get-ActivityAlert
    //Get-AntiPhishPolicy
    //Get-AntiPhishRule
    //Get-AtpPolicyForO365
    //Get-AuditConfig
    //Get-AuditConfigurationPolicy
    //Get-AuditConfigurationRule
    //Get-AutoSensitivityLabelPolicy
    //Get-AutoSensitivityLabelRule
    //Get-BlockedSenderAddress
    //Get-CaseHoldPolicy
    //Get-CaseHoldRule
    //Get-ComplianceRetentionEvent
    //Get-ComplianceRetentionEventType
    //Get-ComplianceTag
    //Get-ComplianceTagStorage
    //Get-DeviceConditionalAccessPolicy
    //Get-DeviceConditionalAccessRule
    //Get-DeviceConfigurationPolicy
    //Get-DeviceConfigurationRule
    //Get-DevicePolicy
    //Get-DeviceTenantPolicy
    //Get-DeviceTenantRule
    //Get-DkimSigningConfig
    //Get-DlpCompliancePolicy
    //Get-DlpComplianceRule
    //Get-DlpEdmSchema
    //Get-DlpKeywordDictionary
    //Get-DlpPolicy
    //Get-DlpPolicyTemplate
    //Get-DlpSensitiveInformationType
    //Get-DlpSensitiveInformationTypeRulePackage
    //Get-HoldCompliancePolicy
    //Get-HoldComplianceRule
    //Get-HostedConnectionFilterPolicy
    //Get-HostedContentFilterPolicy
    //Get-HostedContentFilterRule
    //Get-HostedOutboundSpamFilterPolicy
    //Get-HostedOutboundSpamFilterRule
    //Get-InboundConnector
    //Get-InboxRule
    //Get-InformationBarrierPoliciesApplicationStatus
    //Get-InformationBarrierPolicy
    //Get-InformationBarrierRecipientStatus
    //Get-Label
    //Get-LabelPolicy
    //Get-MalwareFilterPolicy
    //Get-MalwareFilterRule
    //Get-MessageCategory
    //Get-OutboundConnector
    //Get-PerimeterConfig
    //Get-PolicyTipConfig
    //Get-ProtectionAlert
    //Get-RegulatoryComplianceUI
    //Get-RetentionCompliancePolicy
    //Get-RetentionComplianceRule
    //Get-RetentionEvent
    //Get-SafeAttachmentPolicy
    //Get-SafeAttachmentRule
    //Get-SafeLinksPolicy
    //Get-SafeLinksRule
    //Get-SupervisoryReviewActivity
    //Get-SupervisoryReviewPolicyV2
    //Get-SupervisoryReviewRule
    //Get-SweepRule
    //Get-TenantAllowBlockListItems
    //Get-TransportRule
    //Get-TransportRuleAction
    //Get-TransportRulePredicate
    //Get-UnifiedAuditLogRetentionPolicy
    //Import-DlpPolicyCollection
    //Import-TransportRuleCollection
    //Install-UnifiedCompliancePrerequisite
    //Invoke-HoldRemovalAction
    //New-ActivityAlert
    //New-AntiPhishPolicy
    //New-AntiPhishRule
    //New-AuditConfigurationPolicy
    //New-AuditConfigurationRule
    //New-AutoSensitivityLabelPolicy
    //New-AutoSensitivityLabelRule
    //New-CaseHoldPolicy
    //New-CaseHoldRule
    //New-ComplianceRetentionEvent
    //New-ComplianceRetentionEventType
    //New-ComplianceTag
    //New-DeviceConditionalAccessPolicy
    //New-DeviceConditionalAccessRule
    //New-DeviceConfigurationPolicy
    //New-DeviceConfigurationRule
    //New-DeviceTenantPolicy
    //New-DeviceTenantRule
    //New-DkimSigningConfig
    //New-DlpCompliancePolicy
    //New-DlpComplianceRule
    //New-DlpEdmSchema
    //New-DlpFingerprint
    //New-DlpKeywordDictionary
    //New-DlpPolicy
    //New-DlpSensitiveInformationType
    //New-DlpSensitiveInformationTypeRulePackage
    //New-HoldCompliancePolicy
    //New-HoldComplianceRule
    //New-HostedContentFilterPolicy
    //New-HostedContentFilterRule
    //New-HostedOutboundSpamFilterPolicy
    //New-HostedOutboundSpamFilterRule
    //New-InboundConnector
    //New-InboxRule
    //New-InformationBarrierPolicy
    //New-Label
    //New-LabelPolicy
    //New-MalwareFilterPolicy
    //New-MalwareFilterRule
    //New-OutboundConnector
    //New-PolicyTipConfig
    //New-ProtectionAlert
    //New-RetentionCompliancePolicy
    //New-RetentionComplianceRule
    //New-SafeAttachmentPolicy
    //New-SafeAttachmentRule
    //New-SafeLinksPolicy
    //New-SafeLinksRule
    //New-SupervisoryReviewPolicyV2
    //New-SupervisoryReviewRule
    //New-SweepRule
    //New-TenantAllowBlockListItems
    //New-TransportRule
    //New-UnifiedAuditLogRetentionPolicy
    //Remove-ActivityAlert
    //Remove-AntiPhishPolicy
    //Remove-AntiPhishRule
    //Remove-AuditConfigurationPolicy
    //Remove-AuditConfigurationRule
    //Remove-AutoSensitivityLabelPolicy
    //Remove-AutoSensitivityLabelRule
    //Remove-BlockedSenderAddress
    //Remove-CaseHoldPolicy
    //Remove-CaseHoldRule
    //Remove-ComplianceRetentionEventType
    //Remove-ComplianceTag
    //Remove-DeviceConditionalAccessPolicy
    //Remove-DeviceConditionalAccessRule
    //Remove-DeviceConfigurationPolicy
    //Remove-DeviceConfigurationRule
    //Remove-DeviceTenantPolicy
    //Remove-DeviceTenantRule
    //Remove-DlpCompliancePolicy
    //Remove-DlpComplianceRule
    //Remove-DlpEdmSchema
    //Remove-DlpKeywordDictionary
    //Remove-DlpPolicy
    //Remove-DlpSensitiveInformationType
    //Remove-DlpSensitiveInformationTypeRulePackage
    //Remove-HoldCompliancePolicy
    //Remove-HoldComplianceRule
    //Remove-HostedContentFilterPolicy
    //Remove-HostedContentFilterRule
    //Remove-HostedOutboundSpamFilterPolicy
    //Remove-HostedOutboundSpamFilterRule
    //Remove-InboundConnector
    //Remove-InboxRule
    //Remove-InformationBarrierPolicy
    //Remove-Label
    //Remove-LabelPolicy
    //Remove-MalwareFilterPolicy
    //Remove-MalwareFilterRule
    //Remove-OutboundConnector
    //Remove-PolicyTipConfig
    //Remove-ProtectionAlert
    //Remove-RecordLabel
    //Remove-RetentionCompliancePolicy
    //Remove-RetentionComplianceRule
    //Remove-SafeAttachmentPolicy
    //Remove-SafeAttachmentRule
    //Remove-SafeLinksPolicy
    //Remove-SafeLinksRule
    //Remove-SupervisoryReviewPolicyV2
    //Remove-SweepRule
    //Remove-TenantAllowBlockListItems
    //Remove-TransportRule
    //Remove-UnifiedAuditLogRetentionPolicy
    //Rotate-DkimSigningConfig
    //Search-MessageTrackingReport
    //Set-ActivityAlert
    //Set-AntiPhishPolicy
    //Set-AntiPhishRule
    //Set-AtpPolicyForO365
    //Set-AuditConfig
    //Set-AuditConfigurationRule
    //Set-AutoSensitivityLabelPolicy
    //Set-AutoSensitivityLabelRule
    //Set-CaseHoldPolicy
    //Set-CaseHoldRule
    //Set-ComplianceRetentionEventType
    //Set-ComplianceTag
    //Set-DeviceConditionalAccessPolicy
    //Set-DeviceConditionalAccessRule
    //Set-DeviceConfigurationPolicy
    //Set-DeviceConfigurationRule
    //Set-DeviceTenantPolicy
    //Set-DeviceTenantRule
    //Set-DkimSigningConfig
    //Set-DlpCompliancePolicy
    //Set-DlpComplianceRule
    //Set-DlpEdmSchema
    //Set-DlpKeywordDictionary
    //Set-DlpPolicy
    //Set-DlpSensitiveInformationType
    //Set-DlpSensitiveInformationTypeRulePackage
    //Set-HoldCompliancePolicy
    //Set-HoldComplianceRule
    //Set-HostedConnectionFilterPolicy
    //Set-HostedContentFilterPolicy
    //Set-HostedContentFilterRule
    //Set-HostedOutboundSpamFilterPolicy
    //Set-HostedOutboundSpamFilterRule
    //Set-InboundConnector
    //Set-InboxRule
    //Set-InformationBarrierPolicy
    //Set-Label
    //Set-LabelPolicy
    //Set-MalwareFilterPolicy
    //Set-MalwareFilterRule
    //Set-OutboundConnector
    //Set-PerimeterConfig
    //Set-PolicyTipConfig
    //Set-ProtectionAlert
    //Set-RegulatoryComplianceUI
    //Set-RetentionCompliancePolicy
    //Set-RetentionComplianceRule
    //Set-SafeAttachmentPolicy
    //Set-SafeAttachmentRule
    //Set-SafeLinksPolicy
    //Set-SafeLinksRule
    //Set-SupervisoryReviewPolicyV2
    //Set-SupervisoryReviewRule
    //Set-SweepRule
    //Set-TenantAllowBlockListItems
    //Set-TransportRule
    //Set-UnifiedAuditLogRetentionPolicy
    //Start-InformationBarrierPoliciesApplication
    //Stop-InformationBarrierPoliciesApplication
    //Validate-OutboundConnector
    //Validate-RetentionRuleQuery
}